use std::str::FromStr;

grammar;

pub Expr: f64 = {
    <l:Expr> "+" <r:Factor> => l + r,
    <l:Expr> "-" <r:Factor> => l - r,
    Factor,
};

Factor: f64 = {
    <l:Factor> "**" <r:Term> => f64::powf(l, r),
    <l:Factor> "^" <r:Term> => f64::powf(l, r),
    <l:Factor> "*" <r:Term> => l * r,
    <l:Factor> "/" <r:Term> => l / r,
    Term,
};

pub Term = {
    Num,
    "(" <Expr> ")",
};

Num: f64 = {
    r"[\+-]?[1-9][0-9]*(?:\.[0-9]*)?" => f64::from_str(<>).unwrap()
};
